tocatu/Controllers/BandaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tocatu.Context;
using tocatu.Models;

namespace tocatu.Controllers
{
    public class BandaController : Controller
    {
        private readonly TocatuContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public BandaController(TocatuContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Banda
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public async Task<IActionResult> List()
        {
            return View(await _context.Bandas.ToListAsync());
        }
        // GET: Banda/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banda = await _context.Bandas
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (banda == null)
            {
                return NotFound();
            }

            return View(banda);
        }

        // GET: Banda/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Banda/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Estilo,UserId,NombreUsuario,Nombre,Apellido,Mail,Password")] Banda banda)
        {
            if (ModelState.IsValid)
            {
                _context.Add(banda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(banda);
        }

        // GET: Banda/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banda = await _context.Bandas.FindAsync(id);
            if (banda == null)
            {
                return NotFound();
            }
            return View(banda);
        }

        // POST: Banda/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Estilo,UserId,NombreUsuario,Nombre,Apellido,Mail,Password")] Banda banda)
        {
            if (id != banda.UserId)
            {
                return NotFound();
            }
            EventoController e = new EventoController(_context, _hostEnvironment);
            e.ActualizarDatos(banda.Estilo, banda.Nombre, id);
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(banda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BandaExists(banda.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(banda);
        }

        // GET: Banda/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banda = await _context.Bandas
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (banda == null)
            {
                return NotFound();
            }

            return View(banda);
        }

        // POST: Banda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var banda = await _context.Bandas.FindAsync(id);
            //establecemos el valor de BarId del evento en null, ya que sino al borrar el bar se rompe la bd porque el evento esta vinculado al id de bar
            //falta hace que los datos de la banda en el evento vuelvan a estar vacios
            EventoController e = new EventoController(_context, _hostEnvironment);
            e.BorrarIdBanda(id);
            e.EstablecerDatosDeBandaVacios(id);
            _context.Bandas.Remove(banda);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BandaExists(int id)
        {
            return _context.Bandas.Any(e => e.UserId == id);
        }
    }
}

tocatu/Controllers/BarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using tocatu.Context;
using tocatu.Models;

namespace tocatu.Controllers
{
    public class BarController : Controller
    {
        private readonly TocatuContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public BarController(TocatuContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Bar
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> List()
        {
            return View(await _context.Bar.ToListAsync());
        }

        // GET: Bar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bar = await _context.Bar
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (bar == null)
            {
                return NotFound();
            }

            return View(bar);
        }

        // GET: Bar/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Direccion,Capacidad,UserId,NombreUsuario,Nombre,Apellido,Mail,Password")] Bar bar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bar);
        }

        // GET: Bar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bar = await _context.Bar.FindAsync(id);
            if (bar == null)
            {
                return NotFound();
            }
            return View(bar);
        }

        // POST: Bar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Direccion,Capacidad,UserId,NombreUsuario,Nombre,Apellido,Mail,Password")] Bar bar)
        {
            if (id != bar.UserId)
            {
                return NotFound();
            }

            EventoController e = new EventoController(_context, _hostEnvironment);
            e.ActualizarDatos(bar.Capacidad, bar.Direccion, id);


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BarExists(bar.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bar);
        }


        // GET: Bar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bar = await _context.Bar
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (bar == null)
            {
                return NotFound();
            }

            return View(bar);
        }

        // POST: Bar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bar = await _context.Bar.FindAsync(id);
            //Llamamos a un metodo el cual borra los eventos asociados ya que sin bar no hay evento...
            EventoController e = new EventoController(_context, _hostEnvironment);
            e.BorrarEventosAsociados(id);
            _context.Bar.Remove(bar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BarExists(int id)
        {
            return _context.Bar.Any(e => e.UserId == id);
        }
    }
}

tocatu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tocatu</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="@Url.Content("~/img/tocatuLogo.png")" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=The+Nautigal:wght@700&display=swap" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>
<body>
    <header>
        <nav class=" navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">TOCATU</a>
                <div class="">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white mx-3" asp-area="" asp-controller="Bar" asp-action="Index"><i class="fa-solid fa-wine-glass"></i>BARES</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white mx-3" asp-area="" asp-controller="Banda" asp-action="Index"><i class="fa-solid fa-drum"></i>BANDAS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white mx-3" asp-area="" asp-controller="Evento" asp-action="Index"><i class="fa-solid fa-calendar"></i>EVENTOS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - Tocatu
            <span class="mx-3">-</span>
           <i class="fa-brands fa-facebook m-xl-2"></i>
           <i class="fa-brands fa-instagram m-xl-2"></i>
           <i class="fa-brands fa-twitter m-xl-2"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>